version: '3'
services:
    web:
        build: .
        command: bash -c "python manage.py db upgrade && python manage.py run"
        ports:
            - "5000:5000"
        depends_on:
            - redis
            - postgres
        volumes:
            - .:/app
    
    worker:
        build: .
        command: bash -c "python manage.py runworker"
        depends_on:
            - redis
    
    redis:
        image: redis
    
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=pepper
